//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectSkeleton {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectSkeleton.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action.
        /// </summary>
        internal static string ActionCopy_InvalidAction {
            get {
                return ResourceManager.GetString("ActionCopy_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the frames to copy on the slider by dragging a rectangle before attempting to copy..
        /// </summary>
        internal static string ActionCopy_NoSelectionText {
            get {
                return ResourceManager.GetString("ActionCopy_NoSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action.
        /// </summary>
        internal static string ActionDelete_InvalidAction {
            get {
                return ResourceManager.GetString("ActionDelete_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No frames have been selected to delete.  First drag a selection rectangle on the slider..
        /// </summary>
        internal static string ActionDelete_NoSelectionText {
            get {
                return ResourceManager.GetString("ActionDelete_NoSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard is empty.  First select a region by dragging a rectangle on the slider, and then copy the selection using the context menu..
        /// </summary>
        internal static string ActionPaste_EmptyClipbaordText {
            get {
                return ResourceManager.GetString("ActionPaste_EmptyClipbaordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action.
        /// </summary>
        internal static string ActionPaste_InvalidAction {
            get {
                return ResourceManager.GetString("ActionPaste_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Files (*.xml).
        /// </summary>
        internal static string Animation_Files_Filter {
            get {
                return ResourceManager.GetString("Animation_Files_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string ProcessPlay_Play {
            get {
                return ResourceManager.GetString("ProcessPlay_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to begin playing back the skeleton frames one frame at a time..
        /// </summary>
        internal static string ProcessPlay_PressPlay {
            get {
                return ResourceManager.GetString("ProcessPlay_PressPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to stop playing back the skeleton frames..
        /// </summary>
        internal static string ProcessPlay_PressStop {
            get {
                return ResourceManager.GetString("ProcessPlay_PressStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ProcessPlay_Stop {
            get {
                return ResourceManager.GetString("ProcessPlay_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to start recording skeleton snapshots from the kinect..
        /// </summary>
        internal static string ProcessRecord_PressRecord {
            get {
                return ResourceManager.GetString("ProcessRecord_PressRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to stop recording skeleton snapshots from the kinect..
        /// </summary>
        internal static string ProcessRecord_PressStop {
            get {
                return ResourceManager.GetString("ProcessRecord_PressStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string ProcessRecord_Record {
            get {
                return ResourceManager.GetString("ProcessRecord_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ProcessRecord_Stop {
            get {
                return ResourceManager.GetString("ProcessRecord_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please record or open an animation before attempting to save..
        /// </summary>
        internal static string ProcessSave_NoRecording {
            get {
                return ResourceManager.GetString("ProcessSave_NoRecording", resourceCulture);
            }
        }
    }
}
